default_stages: [commit, push]
exclude: "(tests/test_data/.*)|(lib/openmm.patch)"
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-added-large-files
- repo: https://github.com/psf/black
  rev: 22.6.0
  hooks:
  - id: black
# Do not activate pylint hook for now
# - repo: local
#   hooks:
#   - id: pylint
#     name: pylint
#     entry: pylint
#     language: system
#     types: [python]
#     args:
#       [
#         "-rn", # Only display messages
#         "-sn", # Don't display the score
#       ]
