name: xtrimomultimer
channels:
  - conda-forge
  - bioconda
  - pytorch
dependencies:
  - pytorch::pytorch>=1.10
  - conda-forge::python=3.7
  - conda-forge::setuptools=59.5.0
  - conda-forge::pip
  - conda-forge::openmm=7.5.1
  - conda-forge::pdbfixer
  - conda-forge::cudatoolkit==11.3.*
  - conda-forge::cudatoolkit-dev==11.3.*
  - conda-forge::biopython==1.79
  - conda-forge::scipy==1.7.1
  - conda-forge::pyyaml==5.4.1
  - conda-forge::dm-tree==0.1.6
  - conda-forge::requests==2.26.0
  - conda-forge::pytorch-lightning==1.5.10
  - conda-forge::pandas==1.3.5
  - conda-forge::einops==0.4.1
  - bioconda::hmmer==3.3.2
  - bioconda::hhsuite==3.3.0
  - bioconda::kalign2==2.04
  - pip:
    - deepspeed==0.5.3
    - ml-collections==0.1.0
    - colossalai
